/**
 * @file Fee_PBCfg.h
 * @brief Flash EEPROM Emulation Configuration (Post-Build) - Generated File
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * Generated by: GachBoot ConfigTool (Fee Module)
 * Project: GachBoot v1.0.0
 * Generated: 2025-12-21 15:06:04
 * 
 * This file contains Fee (Flash EEPROM Emulation) configuration:
 * - Virtual address space definition
 * - Sector mapping to Fls physical sectors
 * - Wear leveling parameters
 * - Write alignment settings
 */

#ifndef FEE_PBCFG_H
#define FEE_PBCFG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>

/* ============================================================================
 * Virtual Address Space Configuration (Generated)
 * ============================================================================ */

/**
 * @brief Fee provides continuous virtual address space for NvM
 * 
 * Virtual space: 0x0 - 0x1ffff (128KB)
 * Physical space: Ping-pongs between Fee sectors for wear leveling
 * 
 * NvM sees only virtual addresses.
 * Fee transparently maps virtual → physical.
 */
#define FEE_CFG_VIRTUAL_START           0x0     /**< Virtual address start */
#define FEE_CFG_VIRTUAL_SIZE            (131072U)        /**< 128KB virtual space */
#define FEE_CFG_VIRTUAL_END             (FEE_CFG_VIRTUAL_START + FEE_CFG_VIRTUAL_SIZE - 1U)

/* ============================================================================
 * Wear Leveling Configuration (Generated)
 * ============================================================================ */

/**
 * @brief Sector switch threshold
 * 
 * When active sector usage exceeds this threshold, Fee switches to alternate sector.
 * Leave margin for sector header and metadata.
 */
#define FEE_CFG_SECTOR_FULL_THRESHOLD   (130048U)  /**< 127KB (leave 1KB margin) */

/**
 * @brief Write alignment
 * 
 * Must match Fls write alignment requirement.
 * All Fee writes are aligned to this boundary.
 */
#define FEE_CFG_WRITE_ALIGNMENT         32U             /**< 32 bytes */

/**
 * @brief Erase value
 * 
 * Value of erased flash memory (typically 0xFF for NOR flash).
 */
#define FEE_CFG_ERASE_VALUE             0xff           /**< Erased flash value */

/* ============================================================================
 * Fee Sector Configuration (Generated)
 * ============================================================================ */

/**
 * @brief Fee sector descriptor
 * 
 * Maps Fee logical sectors to physical Fls sectors.
 * Fee ping-pongs between these sectors for wear leveling.
 */
typedef struct {
    uint8_t fls_sector_index;       /**< Index in Fls_SectorTable[] */
    bool is_primary;                /**< Primary sector flag (used first) */
    const char *name;               /**< Human-readable name */
} Fee_SectorConfig_t;

/**
 * @brief Complete Fee configuration
 * 
 * Contains all generated configuration data.
 * Passed to Fee_Init() at runtime.
 */
typedef struct {
    const Fee_SectorConfig_t *sector_table;     /**< Pointer to Fee sector array */
    uint8_t sector_count;                       /**< Number of Fee sectors */
    uint32_t virtual_start;                     /**< Virtual address start */
    uint32_t virtual_size;                      /**< Virtual address space size */
    uint32_t sector_full_threshold;             /**< Sector switch threshold */
    uint32_t write_alignment;                   /**< Write alignment */
    uint8_t erase_value;                        /**< Erased flash value */
} Fee_ConfigType;

/* ============================================================================
 * Generated Configuration Instances
 * ============================================================================ */

/**
 * @brief Fee sector table
 * 
 * Maps 2 Fee logical sectors to Fls physical sectors.
 * Fee alternates between these for wear leveling.
 */
extern const Fee_SectorConfig_t Fee_SectorTable[];
extern const uint8_t Fee_SectorCount;

/**
 * @brief Default Fee configuration
 * 
 * Pre-configured with generated values.
 * Pass to Fee_Init(&Fee_Config) to initialize.
 */
extern const Fee_ConfigType Fee_Config;

#ifdef __cplusplus
}
#endif

#endif /* FEE_PBCFG_H */
