/**
 * @file Fee_PBCfg.c
 * @brief Flash EEPROM Emulation Configuration Implementation (Post-Build)
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * Generated by: GachBoot ConfigTool (Fee Module)
 * Project: GachBoot v1.0.0
 * Generated: 2025-12-27 21:38:25
 * 
 * This file contains the Fee sector mapping and configuration implementation.
 */

#include "Fee_PBCfg.h"

/* ============================================================================
 * Generated Fee Sector Table
 * ============================================================================ */

/**
 * @brief Fee sector mapping
 * 
 * Configuration: 2 Fee sectors
 * Wear leveling: Ping-pong between these sectors
 */
const Fee_SectorConfig_t Fee_SectorTable[] = {
    /* Fee Sector 0 - Primary */
    {
        .fls_sector_index = 0U,  /* Maps to Fls_SectorTable[0] */
        .is_primary = true,
        .name = "Fee_Primary"
    },
    
    /* Fee Sector 1 */
    {
        .fls_sector_index = 1U,  /* Maps to Fls_SectorTable[1] */
        .is_primary = false,
        .name = "Fee_Secondary"
    }
};

const uint8_t Fee_SectorCount = sizeof(Fee_SectorTable) / sizeof(Fee_SectorConfig_t);

/* ============================================================================
 * Generated Fee Configuration Instance
 * ============================================================================ */

/**
 * @brief Default Fee configuration
 * 
 * Pre-configured with all generated parameters.
 * Pass this to Fee_Init(&Fee_Config) to initialize the driver.
 */
const Fee_ConfigType Fee_Config = {
    .sector_table = Fee_SectorTable,
    .sector_count = sizeof(Fee_SectorTable) / sizeof(Fee_SectorConfig_t),
    .virtual_start = FEE_CFG_VIRTUAL_START,
    .virtual_size = FEE_CFG_VIRTUAL_SIZE,
    .sector_full_threshold = FEE_CFG_SECTOR_FULL_THRESHOLD,
    .write_alignment = FEE_CFG_WRITE_ALIGNMENT,
    .erase_value = FEE_CFG_ERASE_VALUE
};

/* End of generated Fee configuration */
