/**
 * @file dev_flashblock.c
 * @brief Flash block management with 3-step erase state machine
 */

#include "dev_flashblock.h"
#include "dev_fls.h"
#include "dev_common.h"
#include "dev_queue.h"
#include "Fls_PBCfg.h"
#include "Flashblock_PBCfg.h"  // Generated configuration
#include <string.h>

CONFIG_LOG_TAG(FLASHBLOCK, true)

/* ===== Configuration from Generated Code ===== */
/* All configuration constants are defined in Flashblock_PBCfg.h (generated by ConfigTool) */
/* Do NOT hardcode values here - modify gachboot_config.json instead */

#define FLASHBLOCK_QUEUE_SIZE          FLASHBLOCK_CFG_QUEUE_SIZE
#define FLASHBLOCK_MAX_DATA_SIZE       FLASHBLOCK_CFG_MAX_DATA_SIZE
#define FLASHBLOCK_WRITE_CHUNK_SIZE    FLASHBLOCK_CFG_WRITE_CHUNK_SIZE

/* ===== Private Data Structures ===== */

/**
 * @brief Flash operation type
 */
typedef enum {
    FLASHBLOCK_OP_ERASE = 0,
    FLASHBLOCK_OP_WRITE
} flashblock_op_type_t;

/**
 * @brief Queued flash operation
 */
typedef struct {
    flashblock_op_type_t op_type;              /**< Operation type */
    uint32_t address;                          /**< Flash address */
    uint32_t length;                           /**< Data length */
    uint8_t data[FLASHBLOCK_MAX_DATA_SIZE];    /**< Data buffer (for writes) */
    dev_flashblock_completion_cb_t callback;   /**< Completion callback */
    void *context;                             /**< User context */
} flashblock_operation_t;

/**
 * @brief Processing context for current operation
 */
typedef struct {
    uint32_t first_sector_idx;     /**< First sector to erase */
    uint32_t last_sector_idx;      /**< Last sector to erase */
    uint32_t current_sector_idx;   /**< Current sector */
    uint32_t bytes_processed;      /**< Bytes written so far */
    uint32_t total_bytes;          /**< Total bytes to write */
} process_context_t;

/**
 * @brief Flash block module state
 */
typedef struct {
    bool initialized;                          /**< Initialization flag */
    dev_flashblock_config_t config;            /**< Configuration */
    dev_flashblock_state_t state;              /**< Current state */
    dev_queue_t operation_queue;               /**< Operation queue */
    flashblock_operation_t queue_buffer[FLASHBLOCK_QUEUE_SIZE];  /**< Queue storage */
    flashblock_operation_t current_op;         /**< Current processing operation */
    process_context_t process_ctx;             /**< Processing context */
} flashblock_state_t;

/* ===== Private Variables ===== */

static flashblock_state_t g_flashblock = {
    .initialized = false,
    .state = DEV_FLASHBLOCK_STATE_IDLE
};

/* ===== Private Helper Functions ===== */

/**
 * @brief Check if address is in valid flash range
 */
static bool is_valid_flash_address(uint32_t address, uint32_t length)
{
    if (length == 0) {
        return false;
    }
    
    uint32_t end_address = address + length - 1;
    
    // Check if entire range is within flash memory region
    for (uint32_t i = 0; i < Fls_SectorCount; i++) {
        uint32_t sector_start = Fls_SectorTable[i].base_address;
        uint32_t sector_end = sector_start + Fls_SectorTable[i].size - 1;
        
        // Check if range starts in this sector
        if (address >= sector_start && address <= sector_end) {
            // Check if range also ends within valid flash space
            if (end_address <= sector_end) {
                return true;
            }
            // Range spans multiple sectors - need to verify continuity
            // For now, allow it if it doesn't exceed last sector
            if (i < Fls_SectorCount - 1) {
                continue;
            }
        }
    }
    
    // Check last sector
    if (Fls_SectorCount > 0) {
        uint32_t last_idx = Fls_SectorCount - 1;
        uint32_t last_sector_end = Fls_SectorTable[last_idx].base_address + 
                                   Fls_SectorTable[last_idx].size - 1;
        if (end_address <= last_sector_end) {
            return true;
        }
    }
    
    return false;
}

/**
 * @brief Find sector index containing the given address
 */
static int32_t find_sector_by_address(uint32_t address)
{
    for (uint32_t i = 0; i < Fls_SectorCount; i++) {
        uint32_t sector_start = Fls_SectorTable[i].base_address;
        uint32_t sector_end = sector_start + Fls_SectorTable[i].size;
        
        if (address >= sector_start && address < sector_end) {
            return (int32_t)i;
        }
    }
    
    return -1;  // Not found
}

/**
 * @brief Determine which sectors need to be erased
 * 
 * @param address Start address
 * @param length Length in bytes
 * @param first_sector Output: Index of first sector to erase
 * @param last_sector Output: Index of last sector to erase
 * @return true if sectors found, false otherwise
 */
static bool determine_erase_sectors(uint32_t address, uint32_t length,
                                     uint32_t *first_sector, uint32_t *last_sector)
{
    int32_t first_idx = find_sector_by_address(address);
    if (first_idx < 0) {
        DBG_OUT_E("Start address 0x%08X not in any sector", address);
        return false;
    }
    
    uint32_t end_address = address + length - 1;
    int32_t last_idx = find_sector_by_address(end_address);
    if (last_idx < 0) {
        DBG_OUT_E("End address 0x%08X not in any sector", end_address);
        return false;
    }
    
    *first_sector = (uint32_t)first_idx;
    *last_sector = (uint32_t)last_idx;
    
    DBG_OUT_I("Erase range: sectors %u to %u (total: %u sectors)",
              *first_sector, *last_sector, (*last_sector - *first_sector + 1));
    
    return true;
}

/* ===== Public API Implementation ===== */

dev_flashblock_result_t dev_flashblock_init(const dev_flashblock_config_t *config)
{
    // Apply configuration
    if (config != NULL) {
        memcpy(&g_flashblock.config, config, sizeof(dev_flashblock_config_t));
    } else {
        // Default configuration from generated config
        g_flashblock.config.write_alignment = FLASHBLOCK_CFG_WRITE_CHUNK_SIZE;
        g_flashblock.config.erase_timeout_ms = FLASHBLOCK_CFG_ERASE_TIMEOUT_MS;
        g_flashblock.config.write_timeout_ms = FLASHBLOCK_CFG_WRITE_TIMEOUT_MS;
        g_flashblock.config.auto_verify = (bool)FLASHBLOCK_CFG_AUTO_VERIFY;
        g_flashblock.config.progress_cb = NULL;
        g_flashblock.config.context = NULL;
    }
    
    // Initialize operation queue
    dev_queue_result_t queue_result = dev_queue_init(
        &g_flashblock.operation_queue,
        g_flashblock.queue_buffer,
        sizeof(g_flashblock.queue_buffer),
        sizeof(flashblock_operation_t)
    );
    
    if (queue_result != DEV_QUEUE_OK) {
        DBG_OUT_E("Failed to initialize operation queue: %s",
                  dev_queue_get_error_string(queue_result));
        return DEV_FLASHBLOCK_ERROR_NOT_INIT;
    }
    
    // Initialize state
    g_flashblock.state = DEV_FLASHBLOCK_STATE_IDLE;
    memset(&g_flashblock.current_op, 0, sizeof(flashblock_operation_t));
    memset(&g_flashblock.process_ctx, 0, sizeof(process_context_t));
    g_flashblock.initialized = true;
    
    DBG_OUT_I("Flash block initialized - queue capacity: %u operations",
              dev_queue_capacity(&g_flashblock.operation_queue));
    
    return DEV_FLASHBLOCK_OK;
}

/* ===== Public API Implementation ===== */

dev_flashblock_result_t dev_flashblock_erase_async(
    uint32_t address,
    uint32_t length,
    dev_flashblock_completion_cb_t callback,
    void *context
)
{
    // Check initialization
    if (!g_flashblock.initialized) {
        DBG_OUT_E("Module not initialized");
        return DEV_FLASHBLOCK_ERROR_NOT_INIT;
    }
    
    // Validate parameters
    if (length == 0) {
        DBG_OUT_E("Invalid length: 0");
        return DEV_FLASHBLOCK_ERROR_INVALID_LEN;
    }
    
    if (!is_valid_flash_address(address, length)) {
        DBG_OUT_E("Invalid flash range: 0x%08X - 0x%08X", address, address + length - 1);
        return DEV_FLASHBLOCK_ERROR_INVALID_ADDR;
    }
    
    // Check if queue has space
    if (dev_queue_is_full(&g_flashblock.operation_queue)) {
        DBG_OUT_W("Operation queue full");
        return DEV_FLASHBLOCK_ERROR_BUSY;
    }
    
    // Create operation
    flashblock_operation_t op = {
        .op_type = FLASHBLOCK_OP_ERASE,
        .address = address,
        .length = length,
        .callback = callback,
        .context = context
    };
    
    // Enqueue operation
    dev_queue_result_t result = dev_queue_enqueue(&g_flashblock.operation_queue, &op);
    if (result != DEV_QUEUE_OK) {
        DBG_OUT_E("Failed to enqueue erase: %s", dev_queue_get_error_string(result));
        return DEV_FLASHBLOCK_ERROR_BUSY;
    }
    
    DBG_OUT_I("Erase enqueued - addr=0x%08X, len=%u (queue: %u/%u)",
              address, length,
              dev_queue_count(&g_flashblock.operation_queue),
              dev_queue_capacity(&g_flashblock.operation_queue));
    
    return DEV_FLASHBLOCK_OK;
}

dev_flashblock_result_t dev_flashblock_write_async(
    uint32_t address,
    const uint8_t *data,
    uint32_t length,
    dev_flashblock_completion_cb_t callback,
    void *context
)
{
    // Check initialization
    if (!g_flashblock.initialized) {
        DBG_OUT_E("Module not initialized");
        return DEV_FLASHBLOCK_ERROR_NOT_INIT;
    }
    
    // Validate parameters
    if (data == NULL) {
        DBG_OUT_E("NULL data pointer");
        return DEV_FLASHBLOCK_ERROR_INVALID_LEN;
    }
    
    if (length == 0 || length > FLASHBLOCK_MAX_DATA_SIZE) {
        DBG_OUT_E("Invalid length: %u (max: %u)", length, FLASHBLOCK_MAX_DATA_SIZE);
        return DEV_FLASHBLOCK_ERROR_INVALID_LEN;
    }
    
    if (!is_valid_flash_address(address, length)) {
        DBG_OUT_E("Invalid flash range: 0x%08X - 0x%08X", address, address + length - 1);
        return DEV_FLASHBLOCK_ERROR_INVALID_ADDR;
    }
    
    // Check if queue has space
    if (dev_queue_is_full(&g_flashblock.operation_queue)) {
        DBG_OUT_W("Operation queue full");
        return DEV_FLASHBLOCK_ERROR_BUSY;
    }
    
    // Create operation (copy data to internal buffer)
    flashblock_operation_t op = {
        .op_type = FLASHBLOCK_OP_WRITE,
        .address = address,
        .length = length,
        .callback = callback,
        .context = context
    };
    memcpy(op.data, data, length);
    
    // Enqueue operation
    dev_queue_result_t result = dev_queue_enqueue(&g_flashblock.operation_queue, &op);
    if (result != DEV_QUEUE_OK) {
        DBG_OUT_E("Failed to enqueue write: %s", dev_queue_get_error_string(result));
        return DEV_FLASHBLOCK_ERROR_BUSY;
    }
    
    DBG_OUT_I("Write enqueued - addr=0x%08X, len=%u (queue: %u/%u)",
              address, length,
              dev_queue_count(&g_flashblock.operation_queue),
              dev_queue_capacity(&g_flashblock.operation_queue));
    
    return DEV_FLASHBLOCK_OK;
}

/**
 * @brief Process erase operation (handles one sector per call)
 */
static dev_flashblock_result_t process_erase_operation(void)
{
    // Check if erase is starting
    if (g_flashblock.process_ctx.current_sector_idx == 0) {
        // Determine sectors to erase
        if (!determine_erase_sectors(
            g_flashblock.current_op.address,
            g_flashblock.current_op.length,
            &g_flashblock.process_ctx.first_sector_idx,
            &g_flashblock.process_ctx.last_sector_idx))
        {
            return DEV_FLASHBLOCK_ERROR_INVALID_ADDR;
        }
        
        g_flashblock.process_ctx.current_sector_idx = g_flashblock.process_ctx.first_sector_idx;
        g_flashblock.process_ctx.total_bytes = g_flashblock.process_ctx.last_sector_idx - 
                                               g_flashblock.process_ctx.first_sector_idx + 1;
        
        DBG_OUT_I("Starting erase - sectors %u to %u",
                  g_flashblock.process_ctx.first_sector_idx,
                  g_flashblock.process_ctx.last_sector_idx);
    }
    
    // Erase current sector
    uint32_t sector_idx = g_flashblock.process_ctx.current_sector_idx;
    
    if (sector_idx <= g_flashblock.process_ctx.last_sector_idx) {
        DBG_OUT_I("Erasing sector %u...", sector_idx);
        
        dev_err_t result = dev_fls_erase_sector((uint8_t)sector_idx);
        if (result != DEV_OK) {
            DBG_OUT_E("Sector %u erase failed: %d", sector_idx, result);
            return DEV_FLASHBLOCK_ERROR_ERASE;
        }
        
        g_flashblock.process_ctx.current_sector_idx++;
        g_flashblock.process_ctx.bytes_processed++;
        
        // Report progress
        if (g_flashblock.config.progress_cb != NULL) {
            g_flashblock.config.progress_cb(
                g_flashblock.process_ctx.bytes_processed,
                g_flashblock.process_ctx.total_bytes,
                g_flashblock.config.context
            );
        }
        
        // Check if more sectors to erase
        if (g_flashblock.process_ctx.current_sector_idx <= g_flashblock.process_ctx.last_sector_idx) {
            return DEV_FLASHBLOCK_ERROR_BUSY;  // More work to do
        }
    }
    
    DBG_OUT_I("Erase completed - %u sectors erased", g_flashblock.process_ctx.total_bytes);
    return DEV_FLASHBLOCK_OK;
}

/**
 * @brief Process write operation (handles 32-byte chunks)
 */
static dev_flashblock_result_t process_write_operation(void)
{
    // Initialize on first call
    if (g_flashblock.process_ctx.bytes_processed == 0) {
        g_flashblock.process_ctx.total_bytes = g_flashblock.current_op.length;
        DBG_OUT_I("Starting write - addr=0x%08X, len=%u",
                  g_flashblock.current_op.address,
                  g_flashblock.current_op.length);
    }
    
    // Calculate current chunk
    uint32_t remaining = g_flashblock.process_ctx.total_bytes - g_flashblock.process_ctx.bytes_processed;
    uint32_t chunk_size = (remaining > FLASHBLOCK_WRITE_CHUNK_SIZE) ? 
                          FLASHBLOCK_WRITE_CHUNK_SIZE : remaining;
    
    // Prepare chunk (pad to 32 bytes if needed)
    uint8_t chunk_buffer[FLASHBLOCK_WRITE_CHUNK_SIZE] = {0xFF};
    memcpy(chunk_buffer, 
           &g_flashblock.current_op.data[g_flashblock.process_ctx.bytes_processed],
           chunk_size);
    
    // Calculate current address
    uint32_t current_addr = g_flashblock.current_op.address + g_flashblock.process_ctx.bytes_processed;
    
    // Write chunk
    dev_err_t result = dev_fls_write(current_addr, chunk_buffer, FLASHBLOCK_WRITE_CHUNK_SIZE);
    if (result != DEV_OK) {
        DBG_OUT_E("Write failed at 0x%08X: %d", current_addr, result);
        return DEV_FLASHBLOCK_ERROR_WRITE;
    }
    
    g_flashblock.process_ctx.bytes_processed += chunk_size;
    
    // Report progress
    if (g_flashblock.config.progress_cb != NULL) {
        g_flashblock.config.progress_cb(
            g_flashblock.process_ctx.bytes_processed,
            g_flashblock.process_ctx.total_bytes,
            g_flashblock.config.context
        );
    }
    
    // Check if more data to write
    if (g_flashblock.process_ctx.bytes_processed < g_flashblock.process_ctx.total_bytes) {
        return DEV_FLASHBLOCK_ERROR_BUSY;  // More work to do
    }
    
    DBG_OUT_I("Write completed - %u bytes written", g_flashblock.process_ctx.total_bytes);
    return DEV_FLASHBLOCK_OK;
}

void dev_flashblock_process(void)
{
    // Check if not initialized
    if (!g_flashblock.initialized) {
        return;
    }
    
    // If IDLE, try to dequeue next operation
    if (g_flashblock.state == DEV_FLASHBLOCK_STATE_IDLE) {
        if (dev_queue_is_empty(&g_flashblock.operation_queue)) {
            return;  // Nothing to do
        }
        
        // Dequeue next operation
        dev_queue_result_t result = dev_queue_dequeue(&g_flashblock.operation_queue, &g_flashblock.current_op);
        if (result != DEV_QUEUE_OK) {
            DBG_OUT_E("Failed to dequeue operation: %s", dev_queue_get_error_string(result));
            return;
        }
        
        // Reset processing context
        memset(&g_flashblock.process_ctx, 0, sizeof(process_context_t));
        g_flashblock.state = DEV_FLASHBLOCK_STATE_BUSY;
        
        DBG_OUT_I("Processing %s operation (queue: %u remaining)",
                  (g_flashblock.current_op.op_type == FLASHBLOCK_OP_ERASE) ? "erase" : "write",
                  dev_queue_count(&g_flashblock.operation_queue));
    }
    
    // Process current operation
    if (g_flashblock.state == DEV_FLASHBLOCK_STATE_BUSY) {
        dev_flashblock_result_t result;
        
        if (g_flashblock.current_op.op_type == FLASHBLOCK_OP_ERASE) {
            result = process_erase_operation();
        } else {
            result = process_write_operation();
        }
        
        // Check if operation completed
        if (result == DEV_FLASHBLOCK_ERROR_BUSY) {
            // Still processing, will continue next call
            return;
        }
        
        // Operation completed (success or error)
        g_flashblock.state = DEV_FLASHBLOCK_STATE_IDLE;
        
        // Invoke completion callback
        if (g_flashblock.current_op.callback != NULL) {
            g_flashblock.current_op.callback(result, g_flashblock.current_op.context);
        }
        
        if (result == DEV_FLASHBLOCK_OK) {
            DBG_OUT_I("Operation completed successfully");
        } else {
            DBG_OUT_E("Operation failed: %s", dev_flashblock_get_error_string(result));
        }
    }
}

dev_flashblock_state_t dev_flashblock_get_state(void)
{
    return g_flashblock.state;
}

uint8_t dev_flashblock_get_queue_count(void)
{
    if (!g_flashblock.initialized) {
        return 0;
    }
    return (uint8_t)dev_queue_count(&g_flashblock.operation_queue);
}

bool dev_flashblock_is_busy(void)
{
    return (g_flashblock.state != DEV_FLASHBLOCK_STATE_IDLE);
}

const char* dev_flashblock_get_error_string(dev_flashblock_result_t result)
{
    switch (result) {
        case DEV_FLASHBLOCK_OK:
            return "Success";
        case DEV_FLASHBLOCK_ERROR_INVALID_ADDR:
            return "Invalid flash address";
        case DEV_FLASHBLOCK_ERROR_INVALID_LEN:
            return "Invalid length";
        case DEV_FLASHBLOCK_ERROR_ALIGNMENT:
            return "Alignment error";
        case DEV_FLASHBLOCK_ERROR_ERASE:
            return "Erase operation failed";
        case DEV_FLASHBLOCK_ERROR_WRITE:
            return "Write operation failed";
        case DEV_FLASHBLOCK_ERROR_VERIFY:
            return "Verification failed";
        case DEV_FLASHBLOCK_ERROR_BUSY:
            return "Flash controller busy";
        case DEV_FLASHBLOCK_ERROR_TIMEOUT:
            return "Operation timeout";
        case DEV_FLASHBLOCK_ERROR_NOT_INIT:
            return "Module not initialized";
        case DEV_FLASHBLOCK_ERROR_INVALID_STATE:
            return "Invalid state for operation";
        default:
            return "Unknown error";
    }
}
