/**
 * @file DID_PBCfg.h
 * @brief DID Registry Declarations
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * Generated by: GachBoot ConfigTool (DID Module)
 * Project: GachBoot v1.0.0
 * Generated: 2026-01-27 22:26:34
 */

#ifndef DID_PBCFG_H
#define DID_PBCFG_H

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>



/* ========================================================================== */
/*                              Type Definitions                              */
/* ========================================================================== */
// Forward declare Std_ReturnType if not already defined

#ifndef STD_TYPES_H
typedef uint8_t Std_ReturnType;
typedef uint8_t ErrorCode_t;
#define E_OK        0x00u
#define E_NOT_OK    0x01u
#endif

/**
 * @brief DID read callback function type
 * 
 * @param data      Output buffer to fill with DID data
 * @return Std_ReturnType E_OK if success, E_NOT_OK if failed
 * 
 * @note Callback must fill 'data' buffer with DID value
 *       Buffer size is guaranteed to be >= expected_length
 */
typedef Std_ReturnType (*uds_did_read_callback_t)(uint8_t *data);

/**
 * @brief DID write callback function type
 * 
 * @param data      Input data to write
 * @param length    Length of input data
 * @return Std_ReturnType E_OK if success, E_NOT_OK if failed
 * 
 * @note Callback must validate and process input data
 *       Length is pre-validated against expected_length range
 */
typedef Std_ReturnType (*uds_did_write_callback_t)(const uint8_t *data, ErrorCode_t * ErrorCode);

/**
 * @brief DID IO control callback function type (Future: Service 0x2F)
 * 
 * @param control_option    Control option parameter
 * @param control_param     Control parameter data
 * @param param_length      Length of control parameter
 * @param state_record      Output buffer for control state record
 * @param state_length      Output length of state record
 * @return Std_ReturnType E_OK if success, E_NOT_OK if failed
 */
typedef Std_ReturnType (*uds_did_io_control_callback_t)(
    uint8_t control_option,
    const uint8_t *control_param,
    uint16_t param_length,
    uint8_t *state_record,
    uint16_t *state_length
);

/**
 * @brief DID dynamic length getter function type
 * 
 * @return uint16_t Current length of DID data (for variable length DIDs)
 * 
 * @note Only used if expected_length = 0 (variable length)
 *       Return 0 if DID has no data available
 */
typedef uint16_t (*uds_did_length_getter_t)(void);

/**
 * @brief DID registry entry structure
 * 
 * This structure defines a complete DID configuration including:
 * - Basic properties (ID, length)
 * - Service-specific callbacks
 * - Service-specific access control (session/security)
 * - Data validation settings
 */
typedef struct {
    /* ===== Basic DID Properties ===== */
    uint16_t did;                           /**< Data Identifier (0x0000 - 0xFFFF) */
    uint16_t expected_length;               /**< Expected data length (0 = variable) */
    uint16_t min_length;                    /**< Minimum length (for variable DIDs) */
    uint16_t max_length;                    /**< Maximum length (for variable DIDs) */
    
    /* ===== Service 0x22 (Read Data By Identifier) ===== */
    struct {
        uds_did_read_callback_t callback;   /**< Read callback function */
        uds_did_length_getter_t length_getter; /**< Dynamic length getter (if variable) */
        uint32_t session_mask;              /**< Allowed sessions (UDS_SESSION_MASK_xxx) */
        uint32_t security_mask;             /**< Required security level (UDS_SECURITY_MASK_xxx) */
    } read_config;
    
    /* ===== Service 0x2E (Write Data By Identifier) ===== */
    struct {
        uds_did_write_callback_t callback;  /**< Write callback function */
        uint32_t session_mask;              /**< Allowed sessions */
        uint32_t security_mask;             /**< Required security level */
        bool semantic_validation;           /**< Enable semantic validation */
    } write_config;
    
    /* ===== Service 0x2F (Input Output Control By Identifier) - Future ===== */
    struct {
        uds_did_io_control_callback_t callback; /**< IO control callback */
        uint32_t session_mask;              /**< Allowed sessions */
        uint32_t security_mask;             /**< Required security level */
        uint8_t supported_options;          /**< Supported control options bitmask */
    } io_control_config;
    
} uds_did_entry_t;


// DID Identifiers
#define DID_VIN  0xF190

// Total DID count
#define UDS_DID_COUNT_GENERATED 1

// Generated DID Registry
extern const uds_did_entry_t uds_did_registry_generated[UDS_DID_COUNT_GENERATED];



/* ========================================================================== */
/*                   Callback Function Declarations                           */
/* ========================================================================== */
// User must implement these callback functions

extern Std_ReturnType uds_did_read_vin(uint8_t *data);

#endif // DID_PBCFG_H
