/**
 * @file DID_PBCfg.c
 * @brief DID Registry Implementation
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * Generated by: GachBoot ConfigTool (DID Module)
 * Project: GachBoot v1.0.0
 * Generated: 2025-12-06 22:18:45
 */

#include "DID_PBCfg.h"
#include <stddef.h>

// DID Registry Table
const uds_did_entry_t uds_did_registry_generated[UDS_DID_COUNT_GENERATED] = {
    // Vehicle Identification Number
    {
        .did = 0xF190,
        .expected_length = 17,
        .min_length = 0,
        .max_length = 0,
        .read_config = {
            .callback = uds_did_read_vin,
            .length_getter = NULL,
            .session_mask = 1,
            .security_mask = 0
        },
        .write_config = {
            .callback = uds_did_write_vin,
            .session_mask = 2,
            .security_mask = 1,
            .semantic_validation = false
        },
        .io_control_config = {
            .callback = NULL,
            .session_mask = 0,
            .security_mask = 0,
            .supported_options = 0
        }
    }
};
