#ifndef BL_TYPES_H
#define BL_TYPES_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

typedef enum
{
    BL_STATUS_OK = 0,
    BL_STATUS_ERROR,
    BL_STATUS_PARAM,
    BL_STATUS_TIMEOUT,
    BL_STATUS_BUSY,
    BL_STATUS_INVALID_STATE,
    BL_STATUS_NOT_SUPPORTED,
    BL_STATUS_CHECKSUM,
    BL_STATUS_IO
} bl_status_t;

typedef enum
{
    BL_ERROR_OK = 0x00u,
    BL_ERROR_INVALID_FRAME = 0x01u,
    BL_ERROR_UNSUPPORTED_VERSION = 0x02u,
    BL_ERROR_UNSUPPORTED_COMMAND = 0x03u,
    BL_ERROR_INVALID_SEQUENCE = 0x04u,
    BL_ERROR_INVALID_LENGTH = 0x05u,
    BL_ERROR_CHECKSUM_MISMATCH = 0x06u,
    BL_ERROR_SESSION_NOT_ACTIVE = 0x07u,
    BL_ERROR_FLASH_ERASE_FAILED = 0x08u,
    BL_ERROR_FLASH_WRITE_FAILED = 0x09u,
    BL_ERROR_FLASH_VERIFY_FAILED = 0x0Au,
    BL_ERROR_FIRMWARE_SIZE_INVALID = 0x0Bu,
    BL_ERROR_FIRMWARE_CHECKSUM_INVALID = 0x0Cu,
    BL_ERROR_FIRMWARE_SIGNATURE_INVALID = 0x0Du,
    BL_ERROR_TIMEOUT = 0x0Eu,
    BL_ERROR_INTERNAL = 0x0Fu,
    BL_ERROR_ABORT_REQUESTED = 0x10u
} bl_error_t;

#endif /* BL_TYPES_H */
