/**
 * @file DCM_Session_PBCfg.c
 * @brief Diagnostic Session Configuration (Auto-generated)
 * @date 2025-12-23 21:09:20
 * 
 * DO NOT MODIFY - Generated by ConfigTool
 */

#include "DCM_Session_PBCfg.h"

/**
 * @brief Diagnostic Session Configuration Table
 */
const svc_dcm_session_config_t svc_dcm_session_table[SVC_DCM_SESSION_COUNT] = {
    /* 0: DCM_DEFAULT_SESSION - Default diagnostic session */
    {
        .session_name = "DCM_DEFAULT_SESSION",
        .session_value = 0x01,
        .session_mask = (1U << 1U)
    },
    /* 1: DCM_PROGRAMMING_SESSION - Programming session for bootloader */
    {
        .session_name = "DCM_PROGRAMMING_SESSION",
        .session_value = 0x02,
        .session_mask = (1U << 2U)
    },
    /* 2: DCM_EXTENDED_SESSION - Extended diagnostic session */
    {
        .session_name = "DCM_EXTENDED_SESSION",
        .session_value = 0x03,
        .session_mask = (1U << 3U)
    }
};
