/**
 * @file DCM_Session_PBCfg.h
 * @brief Diagnostic Session Configuration (Auto-generated)
 * @date 2025-12-21 15:06:03
 * 
 * DO NOT MODIFY - Generated by ConfigTool
 */

#ifndef DCM_SESSION_PBCFG_H
#define DCM_SESSION_PBCFG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>


/**
 * @brief Diagnostic Session Configuration Types
 */

typedef struct {
    const char *session_name;           // Session name (for debugging)
    uint8_t session_value;              // Session value (hex)
    uint32_t session_mask;              // Session mask (1 << session_value)
} svc_dcm_session_config_t;


/* Session Configuration Count */
#define SVC_DCM_SESSION_COUNT  3U

/* Session Value Definitions */
#define DCM_DEFAULT_SESSION_VALUE  0x01
#define DCM_PROGRAMMING_SESSION_VALUE  0x02
#define DCM_EXTENDED_SESSION_VALUE  0x03

/* Session Mask Definitions */
#define DCM_DEFAULT_SESSION_MASK  (1U << 1U)
#define DCM_PROGRAMMING_SESSION_MASK  (1U << 2U)
#define DCM_EXTENDED_SESSION_MASK  (1U << 3U)

/* External Configuration Table */
extern const svc_dcm_session_config_t svc_dcm_session_table[SVC_DCM_SESSION_COUNT];

#ifdef __cplusplus
}
#endif

#endif /* DCM_SESSION_PBCFG_H */
