/**
 * @file Flashblock_PBCfg.h
 * @brief Flash Block Post-Build Configuration (Generated by ConfigTool)
 * 
 * Flash Block Module Configuration - Queue-based async operations
 * 
 * DO NOT EDIT MANUALLY - Changes will be overwritten on next generation.
 * To modify configuration, edit gachboot_config.json and regenerate.
 * 
 * Generated: 2026-01-27 22:26:34
 */

#ifndef FLASHBLOCK_PBCFG_H
#define FLASHBLOCK_PBCFG_H

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Configuration Constants
 * ============================================================================ */

/**
 * @brief Maximum number of queued operations
 * 
 * Defines how many flash operations (erase/write) can be queued
 * simultaneously. Larger values allow more buffering but use more RAM.
 * 
 * Current: 8 operations
 * RAM usage: ~2368 bytes (8 * 296 bytes per entry)
 */
#define FLASHBLOCK_CFG_QUEUE_SIZE          8u

/**
 * @brief Maximum data size per write operation (bytes)
 * 
 * Defines the maximum amount of data that can be written in a single
 * dev_flashblock_write_async() call. Data is buffered internally.
 * 
 * Current: 256 bytes
 * Constraint: Must be multiple of FLASHBLOCK_CFG_WRITE_CHUNK_SIZE (32)
 */
#define FLASHBLOCK_CFG_MAX_DATA_SIZE       256u

/**
 * @brief Flash write chunk size / alignment requirement (bytes)
 * 
 * Defines the flash controller's write alignment requirement.
 * All write operations are split into chunks of this size.
 * 
 * MCU-specific values:
 * - STM32H7: 32 bytes (256-bit ECC flash)
 * - STM32F4: 4 bytes (word-aligned)
 * - STM32L4: 8 bytes (double-word)
 * 
 * Current: 32 bytes
 * 
 * @note CRITICAL: Must match hardware capability!
 */
#define FLASHBLOCK_CFG_WRITE_CHUNK_SIZE    32u

/**
 * @brief Default erase timeout per sector (milliseconds)
 * 
 * Maximum time to wait for a single sector erase to complete.
 * Adjust based on flash sector size and erase time.
 * 
 * Current: 2000ms
 */
#define FLASHBLOCK_CFG_ERASE_TIMEOUT_MS    2000u

/**
 * @brief Default write timeout per chunk (milliseconds)
 * 
 * Maximum time to wait for a single chunk write to complete.
 * Usually much faster than erase.
 * 
 * Current: 100ms
 */
#define FLASHBLOCK_CFG_WRITE_TIMEOUT_MS    100u

/**
 * @brief Enable automatic write verification
 * 
 * When enabled, each write operation is followed by a read-back
 * verification to ensure data integrity.
 * 
 * Current: 0 (Disabled)
 * 0 = Disabled (faster, less safe)
 * 1 = Enabled (slower, more reliable)
 */
#define FLASHBLOCK_CFG_AUTO_VERIFY         0u

/* ============================================================================
 * Configuration Validation
 * ============================================================================ */

/* Validate queue size */
#if FLASHBLOCK_CFG_QUEUE_SIZE < 1 || FLASHBLOCK_CFG_QUEUE_SIZE > 32
#error "FLASHBLOCK_CFG_QUEUE_SIZE must be between 1 and 32"
#endif

/* Validate max data size */
#if FLASHBLOCK_CFG_MAX_DATA_SIZE < FLASHBLOCK_CFG_WRITE_CHUNK_SIZE
#error "FLASHBLOCK_CFG_MAX_DATA_SIZE must be >= FLASHBLOCK_CFG_WRITE_CHUNK_SIZE"
#endif

#if (FLASHBLOCK_CFG_MAX_DATA_SIZE % FLASHBLOCK_CFG_WRITE_CHUNK_SIZE) != 0
#error "FLASHBLOCK_CFG_MAX_DATA_SIZE must be multiple of FLASHBLOCK_CFG_WRITE_CHUNK_SIZE"
#endif

/* Validate chunk size is power of 2 (common hardware requirement) */
#if (FLASHBLOCK_CFG_WRITE_CHUNK_SIZE & (FLASHBLOCK_CFG_WRITE_CHUNK_SIZE - 1)) != 0
#warning "FLASHBLOCK_CFG_WRITE_CHUNK_SIZE should be power of 2 (4, 8, 16, 32, etc.)"
#endif

/* ============================================================================
 * Calculated Constants
 * ============================================================================ */

/**
 * @brief Total RAM usage for operation queue (bytes)
 * 
 * Approximate memory footprint for the flashblock module.
 * Includes queue buffer + operation structures + internal state.
 */
#define FLASHBLOCK_QUEUE_RAM_USAGE_BYTES   2368u

#ifdef __cplusplus
}
#endif

#endif /* FLASHBLOCK_PBCFG_H */
