/**
 * @file Fls_PBCfg.c
 * @brief Flash Driver Configuration Implementation (Post-Build)
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * This file contains the generated sector table and configuration.
 * 
 * Generated by: GachBoot ConfigTool (Flash Module)
 * Project: GachBoot v1.0.0
 * Generated: 2026-01-01 15:57:00
 * MCU: STM32H743VIT6
 */

#include "Fls_PBCfg.h"

/* ============================================================================
 * Generated Sector Table
 * ============================================================================ */

/**
 * @brief Physical sector descriptors
 * 
 * Flash Configuration:
 * - Bank 1, Sector 0: 0x08000000 - 0x0801FFFF (128KB) [Bank1_Sector0] - Bank 1, Sector 0
 * - Bank 1, Sector 1: 0x08020000 - 0x0803FFFF (128KB) [Bank1_Sector1] - Bank 1, Sector 1
 * - Bank 1, Sector 2: 0x08040000 - 0x0805FFFF (128KB) [Bank1_Sector2] - Bank 1, Sector 2
 * - Bank 1, Sector 3: 0x08060000 - 0x0807FFFF (128KB) [Bank1_Sector3] - Bank 1, Sector 3
 * - Bank 1, Sector 4: 0x08080000 - 0x0809FFFF (128KB) [Bank1_Sector4] - Bank 1, Sector 4
 * - Bank 1, Sector 5: 0x080A0000 - 0x080BFFFF (128KB) [Bank1_Sector5] - Bank 1, Sector 5
 * - Bank 1, Sector 6: 0x080C0000 - 0x080DFFFF (128KB) [Bank1_Sector6] - Bank 1, Sector 6
 * - Bank 1, Sector 7: 0x080E0000 - 0x080FFFFF (128KB) [Bank1_Sector7] - Bank 1, Sector 7
 * - Bank 2, Sector 0: 0x08100000 - 0x0811FFFF (128KB) [Bank2_Sector0] - Bank 2, Sector 0
 * - Bank 2, Sector 1: 0x08120000 - 0x0813FFFF (128KB) [Bank2_Sector1] - Bank 2, Sector 1
 * - Bank 2, Sector 2: 0x08140000 - 0x0815FFFF (128KB) [Bank2_Sector2] - Bank 2, Sector 2
 * - Bank 2, Sector 3: 0x08160000 - 0x0817FFFF (128KB) [Bank2_Sector3] - Bank 2, Sector 3
 * - Bank 2, Sector 4: 0x08180000 - 0x0819FFFF (128KB) [Bank2_Sector4] - Bank 2, Sector 4
 * - Bank 2, Sector 5: 0x081A0000 - 0x081BFFFF (128KB) [Bank2_Sector5] - Bank 2, Sector 5
 * - Bank 2, Sector 6: 0x081C0000 - 0x081DFFFF (128KB) [Bank2_Sector6] - Bank 2, Sector 6
 * - Bank 2, Sector 7: 0x081E0000 - 0x081FFFFF (128KB) [Bank2_Sector7] - Bank 2, Sector 7
 * 
 * Total sectors: 16
 */
const Fls_SectorDescriptor_t Fls_SectorTable[] = {
    /* Sector 0 - Bank 1, Sector 0 (Bank 1, Sector 0) */
    {
        .base_address = 0x08000000U,
        .size = 128U * 1024U,
        .bank_index = 1U,
        .sector_index = 0U,
        .erase_value = 0xFFU,
        .name = "Bank1_Sector0"
    },
    
    /* Sector 1 - Bank 1, Sector 1 (Bank 1, Sector 1) */
    {
        .base_address = 0x08020000U,
        .size = 128U * 1024U,
        .bank_index = 1U,
        .sector_index = 1U,
        .erase_value = 0xFFU,
        .name = "Bank1_Sector1"
    },
    
    /* Sector 2 - Bank 1, Sector 2 (Bank 1, Sector 2) */
    {
        .base_address = 0x08040000U,
        .size = 128U * 1024U,
        .bank_index = 1U,
        .sector_index = 2U,
        .erase_value = 0xFFU,
        .name = "Bank1_Sector2"
    },
    
    /* Sector 3 - Bank 1, Sector 3 (Bank 1, Sector 3) */
    {
        .base_address = 0x08060000U,
        .size = 128U * 1024U,
        .bank_index = 1U,
        .sector_index = 3U,
        .erase_value = 0xFFU,
        .name = "Bank1_Sector3"
    },
    
    /* Sector 4 - Bank 1, Sector 4 (Bank 1, Sector 4) */
    {
        .base_address = 0x08080000U,
        .size = 128U * 1024U,
        .bank_index = 1U,
        .sector_index = 4U,
        .erase_value = 0xFFU,
        .name = "Bank1_Sector4"
    },
    
    /* Sector 5 - Bank 1, Sector 5 (Bank 1, Sector 5) */
    {
        .base_address = 0x080A0000U,
        .size = 128U * 1024U,
        .bank_index = 1U,
        .sector_index = 5U,
        .erase_value = 0xFFU,
        .name = "Bank1_Sector5"
    },
    
    /* Sector 6 - Bank 1, Sector 6 (Bank 1, Sector 6) */
    {
        .base_address = 0x080C0000U,
        .size = 128U * 1024U,
        .bank_index = 1U,
        .sector_index = 6U,
        .erase_value = 0xFFU,
        .name = "Bank1_Sector6"
    },
    
    /* Sector 7 - Bank 1, Sector 7 (Bank 1, Sector 7) */
    {
        .base_address = 0x080E0000U,
        .size = 128U * 1024U,
        .bank_index = 1U,
        .sector_index = 7U,
        .erase_value = 0xFFU,
        .name = "Bank1_Sector7"
    },
    
    /* Sector 8 - Bank 2, Sector 0 (Bank 2, Sector 0) */
    {
        .base_address = 0x08100000U,
        .size = 128U * 1024U,
        .bank_index = 2U,
        .sector_index = 0U,
        .erase_value = 0xFFU,
        .name = "Bank2_Sector0"
    },
    
    /* Sector 9 - Bank 2, Sector 1 (Bank 2, Sector 1) */
    {
        .base_address = 0x08120000U,
        .size = 128U * 1024U,
        .bank_index = 2U,
        .sector_index = 1U,
        .erase_value = 0xFFU,
        .name = "Bank2_Sector1"
    },
    
    /* Sector 10 - Bank 2, Sector 2 (Bank 2, Sector 2) */
    {
        .base_address = 0x08140000U,
        .size = 128U * 1024U,
        .bank_index = 2U,
        .sector_index = 2U,
        .erase_value = 0xFFU,
        .name = "Bank2_Sector2"
    },
    
    /* Sector 11 - Bank 2, Sector 3 (Bank 2, Sector 3) */
    {
        .base_address = 0x08160000U,
        .size = 128U * 1024U,
        .bank_index = 2U,
        .sector_index = 3U,
        .erase_value = 0xFFU,
        .name = "Bank2_Sector3"
    },
    
    /* Sector 12 - Bank 2, Sector 4 (Bank 2, Sector 4) */
    {
        .base_address = 0x08180000U,
        .size = 128U * 1024U,
        .bank_index = 2U,
        .sector_index = 4U,
        .erase_value = 0xFFU,
        .name = "Bank2_Sector4"
    },
    
    /* Sector 13 - Bank 2, Sector 5 (Bank 2, Sector 5) */
    {
        .base_address = 0x081A0000U,
        .size = 128U * 1024U,
        .bank_index = 2U,
        .sector_index = 5U,
        .erase_value = 0xFFU,
        .name = "Bank2_Sector5"
    },
    
    /* Sector 14 - Bank 2, Sector 6 (Bank 2, Sector 6) */
    {
        .base_address = 0x081C0000U,
        .size = 128U * 1024U,
        .bank_index = 2U,
        .sector_index = 6U,
        .erase_value = 0xFFU,
        .name = "Bank2_Sector6"
    },
    
    /* Sector 15 - Bank 2, Sector 7 (Bank 2, Sector 7) */
    {
        .base_address = 0x081E0000U,
        .size = 128U * 1024U,
        .bank_index = 2U,
        .sector_index = 7U,
        .erase_value = 0xFFU,
        .name = "Bank2_Sector7"
    }
};

const uint8_t Fls_SectorCount = sizeof(Fls_SectorTable) / sizeof(Fls_SectorDescriptor_t);

/* ============================================================================
 * Generated Configuration Instance
 * ============================================================================ */

/**
 * @brief Default Fls configuration
 * 
 * Pre-configured with all generated parameters.
 * Pass this to Fls_Init(&Fls_Config) to initialize the driver.
 */
const Fls_ConfigType Fls_Config = {
    .sector_table = Fls_SectorTable,
    .sector_count = sizeof(Fls_SectorTable) / sizeof(Fls_SectorDescriptor_t),
    .write_alignment = FLS_CFG_WRITE_ALIGNMENT,
    .read_alignment = FLS_CFG_READ_ALIGNMENT,
    .erase_value = FLS_CFG_ERASE_VALUE,
    .write_timeout_ms = FLS_CFG_WRITE_TIMEOUT_MS,
    .erase_timeout_ms = FLS_CFG_ERASE_TIMEOUT_MS
};
