/**
 * @file Fls_PBCfg.c
 * @brief Flash Driver Configuration Implementation (Post-Build)
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * This file contains the generated sector table and configuration.
 * 
 * Generated by: GachBoot ConfigTool (Flash Module)
 * Project: GachBoot v1.0.0
 * Generated: 2025-12-20 22:36:57
 * MCU: STM32H743VIT6
 */

#include "Fls_PBCfg.h"

/* ============================================================================
 * Generated Sector Table
 * ============================================================================ */

/**
 * @brief Physical sector descriptors
 * 
 * Flash Configuration:
 * - Bank 2, Sector 6: 0x081C0000 - 0x081DFFFF (128KB) [NVM_Sector_A] - Primary NVM storage sector
 * - Bank 2, Sector 7: 0x081E0000 - 0x081FFFFF (128KB) [NVM_Sector_B] - Secondary NVM storage sector
 * 
 * Total sectors: 2
 */
const Fls_SectorDescriptor_t Fls_SectorTable[] = {
    /* Sector 0 - Bank 2, Sector 6 (Primary NVM storage sector) */
    {
        .base_address = 0x081C0000U,
        .size = 128U * 1024U,
        .bank_index = 2U,
        .sector_index = 6U,
        .erase_value = 0xFFU,
        .name = "NVM_Sector_A"
    },
    
    /* Sector 1 - Bank 2, Sector 7 (Secondary NVM storage sector) */
    {
        .base_address = 0x081E0000U,
        .size = 128U * 1024U,
        .bank_index = 2U,
        .sector_index = 7U,
        .erase_value = 0xFFU,
        .name = "NVM_Sector_B"
    }
};

const uint8_t Fls_SectorCount = sizeof(Fls_SectorTable) / sizeof(Fls_SectorDescriptor_t);

/* ============================================================================
 * Generated Configuration Instance
 * ============================================================================ */

/**
 * @brief Default Fls configuration
 * 
 * Pre-configured with all generated parameters.
 * Pass this to Fls_Init(&Fls_Config) to initialize the driver.
 */
const Fls_ConfigType Fls_Config = {
    .sector_table = Fls_SectorTable,
    .sector_count = sizeof(Fls_SectorTable) / sizeof(Fls_SectorDescriptor_t),
    .write_alignment = FLS_CFG_WRITE_ALIGNMENT,
    .read_alignment = FLS_CFG_READ_ALIGNMENT,
    .erase_value = FLS_CFG_ERASE_VALUE,
    .write_timeout_ms = FLS_CFG_WRITE_TIMEOUT_MS,
    .erase_timeout_ms = FLS_CFG_ERASE_TIMEOUT_MS
};
