/**
 * @file Security_PBCfg.h
 * @brief Security Access Configuration (Post-Build) - Generated File
 * @note DO NOT MODIFY - Auto-generated by GachBoot Config Tool v1.0.0
 */

#ifndef SECURITY_PBCFG_H
#define SECURITY_PBCFG_H

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

/* ========================================================================== */
/*                              Type Definitions                              */
/* ========================================================================== */
// Forward declare Std_ReturnType if not already defined

#ifndef STD_TYPES_H
typedef uint8_t Std_ReturnType;
typedef uint8_t ErrorCode_t;
#define E_OK        0x00u
#define E_NOT_OK    0x01u
#endif

/* Security Level Sub-functions */
#define SECURITY_LEVEL_1_REQUEST_SEED  0x01
#define SECURITY_LEVEL_1_SEND_KEY      0x02
#define SECURITY_LEVEL_2_REQUEST_SEED  0x03
#define SECURITY_LEVEL_2_SEND_KEY      0x04

/* Security Level Count */
#define SECURITY_LEVEL_COUNT  2U

/* Security Level Callback Types */
/**
 * @brief Seed generation callback
 * Generate a seed for security access
 * @param security_level Security level (1, 2, ...)
 * @param seed Output seed buffer (max 16 bytes)
 * @return Std_ReturnType E_OK, E_NOT_OK
 */
typedef Std_ReturnType (*uds_security_get_seed_t)(uint8_t security_level, uint8_t *seed);

/**
 * @brief Key comparison callback
 * Compare received key with expected key
 * @param security_level Security level (1, 2, ...)
 * @param key Received key buffer
 * @param seed Previously sent seed buffer
 * @return Std_ReturnType E_OK (key valid), E_NOT_OK (key invalid)
 */
typedef Std_ReturnType (*uds_security_compare_key_t)(uint8_t security_level, const uint8_t *key, const uint8_t *seed);

/**
 * @brief Security level configuration entry (AUTOSAR DcmDspSecurityRow)
 */
typedef struct {
    uint8_t security_level;                     // Security level (1, 2, ...)
    uint8_t security_sub_function_seed;         // Sub-function for request seed (0x01, 0x03, ...)
    uint8_t security_sub_function_key;          // Sub-function for send key (0x02, 0x04, ...)
    uint8_t seed_size;                          // Seed size in bytes
    uint8_t key_size;                           // Key size in bytes
    uint8_t num_failed_security_access;         // Max failed attempts before lockout
    uint32_t security_delay_time_ms;            // Delay time after failed attempts (ms)
    uint32_t session_mask;                      // Allowed sessions for security access
    uds_security_get_seed_t get_seed_callback;  // Seed generation callback
    uds_security_compare_key_t compare_key_callback;  // Key comparison callback
} dcm_security_level_config_t;

/* External callback function declarations (User must implement) */
extern Std_ReturnType security_get_seed_level_1(uint8_t security_level, uint8_t *seed);
extern Std_ReturnType security_compare_key_level_1(uint8_t security_level, const uint8_t *key, const uint8_t *seed);
extern Std_ReturnType security_get_seed_level_2(uint8_t security_level, uint8_t *seed);
extern Std_ReturnType security_compare_key_level_2(uint8_t security_level, const uint8_t *key, const uint8_t *seed);

/* External Security Level Configuration Table */
extern const dcm_security_level_config_t security_level_config_table[SECURITY_LEVEL_COUNT];

#endif /* SECURITY_PBCFG_H */
