/**
 * @file Security_PBCfg.c
 * @brief Security Access Configuration (Post-Build) - Generated File
 * @note DO NOT MODIFY - Auto-generated by GachBoot Config Tool v1.0.0
 */

#include "Security_PBCfg.h"

/* Security Level Configuration Table */
const dcm_security_level_config_t security_level_config_table[SECURITY_LEVEL_COUNT] = {
    { /* Security Level 1 */
        .security_level = 1,
        .security_sub_function_seed = 0x01,
        .security_sub_function_key = 0x02,
        .seed_size = 4,
        .key_size = 4,
        .num_failed_security_access = 3,
        .security_delay_time_ms = 10000,
        .session_mask = 12,  /* DCM_EXTENDED_SESSION, DCM_PROGRAMMING_SESSION */
        .get_seed_callback = security_get_seed_level_1,
        .compare_key_callback = security_compare_key_level_1
    },
    { /* Security Level 2 */
        .security_level = 2,
        .security_sub_function_seed = 0x03,
        .security_sub_function_key = 0x04,
        .seed_size = 8,
        .key_size = 8,
        .num_failed_security_access = 3,
        .security_delay_time_ms = 30000,
        .session_mask = 12,  /* DCM_PROGRAMMING_SESSION, DCM_EXTENDED_SESSION */
        .get_seed_callback = security_get_seed_level_2,
        .compare_key_callback = security_compare_key_level_2
    }
};
