from enum import IntEnum

class ErrorCode(IntEnum):
    OK = 0x00
    INVALID_FRAME = 0x01
    UNSUPPORTED_PROTOCOL_VERSION = 0x02
    UNSUPPORTED_COMMAND = 0x03
    INVALID_SEQUENCE_NUMBER = 0x04
    INVALID_PAYLOAD_LENGTH = 0x05
    CHECKSUM_MISMATCH = 0x06
    SESSION_NOT_ACTIVE = 0x07
    FLASH_ERASE_FAILED = 0x08
    FLASH_WRITE_FAILED = 0x09
    FLASH_VERIFY_FAILED = 0x0A
    FIRMWARE_SIZE_INVALID = 0x0B
    FIRMWARE_CHECKSUM_INVALID = 0x0C
    FIRMWARE_SIGNATURE_INVALID = 0x0D
    TIMEOUT = 0x0E
    INTERNAL_ERROR = 0x0F
    ABORT_REQUESTED = 0x10
