/**
 * @file Fee_Cfg.h
 * @brief Flash EEPROM Emulation Configuration (CODE GENERATED - DO NOT EDIT)
 * 
 * This file is generated by configuration tools and contains:
 * - Virtual address space configuration
 * - Sector mapping to Fls
 * - Wear leveling parameters
 * 
 * AUTOSAR Standard: AUTOSAR_SWS_FlashEEPROMEmulation.pdf
 * Generator: [YOUR_CONFIG_TOOL_NAME]
 * Generated: [TIMESTAMP]
 */

#ifndef FEE_CFG_H
#define FEE_CFG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include "dev_fls.h"

/* ============================================================================
 * Virtual Address Space Configuration (Generated)
 * ============================================================================ */

/**
 * @brief Fee provides continuous virtual address space for NvM
 * 
 * Virtual space: 0x00000000 - 0x0001FFFF (128KB)
 * Physical space: Ping-pongs between 2 Fls sectors (128KB each)
 * 
 * NvM sees only virtual addresses.
 * Fee transparently maps virtual → physical.
 */
#define FEE_CFG_VIRTUAL_START           0x00000000U     /**< Virtual address start */
#define FEE_CFG_VIRTUAL_SIZE            (128U * 1024U)  /**< 128KB virtual space */
#define FEE_CFG_VIRTUAL_END             (FEE_CFG_VIRTUAL_START + FEE_CFG_VIRTUAL_SIZE - 1U)

/* ============================================================================
 * Wear Leveling Configuration (Generated)
 * ============================================================================ */

/**
 * @brief Sector switch threshold
 * 
 * When active sector usage exceeds this threshold, Fee switches to alternate sector.
 * Leave margin for sector header and metadata.
 */
#define FEE_CFG_SECTOR_FULL_THRESHOLD   (127U * 1024U)  /**< 127KB (leave 1KB margin) */

/**
 * @brief Write alignment
 * 
 * Must match Fls write alignment requirement.
 * All Fee writes are aligned to this boundary.
 */
#define FEE_CFG_WRITE_ALIGNMENT         32U             /**< 32 bytes (256-bit) */

/* ============================================================================
 * Fee Sector Configuration (Generated)
 * ============================================================================ */

/**
 * @brief Fee sector descriptor
 * 
 * Maps Fee logical sectors to physical Fls sectors.
 * Fee ping-pongs between these sectors for wear leveling.
 */
typedef struct {
    uint8_t fls_sector_index;       /**< Index in Fls_SectorTable[] */
    bool is_primary;                /**< Primary sector flag (used first) */
    const char *name;               /**< Human-readable name */
} Fee_SectorConfig_t;

/**
 * @brief Complete Fee configuration
 * 
 * Contains all generated configuration data.
 * Passed to Fee_Init() at runtime.
 */
typedef struct {
    const Fee_SectorConfig_t *sector_table;     /**< Pointer to Fee sector array */
    uint8_t sector_count;                       /**< Number of Fee sectors */
    uint32_t virtual_start;                     /**< Virtual address start */
    uint32_t virtual_size;                      /**< Virtual address space size */
    uint32_t sector_full_threshold;             /**< Sector switch threshold */
    uint32_t write_alignment;                   /**< Write alignment */
    const Fls_ConfigType *fls_config;           /**< Reference to Fls config (for sector lookup) */
} Fee_ConfigType;

/* ============================================================================
 * Generated Configuration Instances
 * ============================================================================ */

/**
 * @brief Fee sector table
 * 
 * Maps 2 Fee logical sectors to 2 Fls physical sectors.
 * Fee alternates between these for wear leveling.
 */
extern const Fee_SectorConfig_t Fee_SectorTable[];
extern const uint8_t Fee_SectorCount;

/**
 * @brief Default Fee configuration
 * 
 * Pre-configured with generated values.
 * Pass to Fee_Init(&Fee_Config) to initialize.
 */
extern const Fee_ConfigType Fee_Config;

#ifdef __cplusplus
}
#endif

#endif /* FEE_CFG_H */
