/**
 * @file NvM_PBCfg.h
 * @brief NVM Block Configuration Declarations
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * Generated by: GachBoot ConfigTool (NVM Module)
 * Project: GachBoot v1.0.0
 * Generated: 2025-12-07 16:27:13
 */

#ifndef NVM_PBCFG_H
#define NVM_PBCFG_H

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>



/**
 * @brief NVM Block Management Types (AUTOSAR-like)
 */

// NVM Block Management Type
typedef enum {
    DEV_NVM_BLOCK_NATIVE = 0,           // Single copy (no redundancy)
    DEV_NVM_BLOCK_REDUNDANT = 1         // Dual copy with CRC validation
} dev_nvm_block_type_t;


typedef struct {
    uint16_t block_id;                  // Unique block identifier
    uint16_t block_size;                // Data size in bytes
    const uint8_t *rom_address;         // Default ROM data (const array)
    uint8_t *ram_address;               // RAM mirror address
    dev_nvm_block_type_t block_type;    // Native or Redundant
    bool write_protection;              // Write protection flag
    bool use_crc;                       // Enable CRC validation
} dev_nvm_block_config_t;

// NVM Block Configuration
#define DEV_NVM_MAX_BLOCKS 1

// Block ID Definitions
#define NVM_BLOCK_VIN  0x0001

// Block Configuration Table
extern const dev_nvm_block_config_t dev_nvm_block_config_table[DEV_NVM_MAX_BLOCKS];
extern const uint16_t dev_nvm_block_config_count;

#endif // NVM_PBCFG_H
