/**
 * @file NvM_PBCfg.c
 * @brief NVM Block Configuration Implementation
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * Generated by: GachBoot ConfigTool (NVM Module)
 * Project: GachBoot v1.0.0
 * Generated: 2025-12-20 22:36:57
 */

#include "NvM_PBCfg.h"
#include <stddef.h>

// External Array Declarations (defined by user)
extern const uint8_t rom_default_vin[17];
extern uint8_t ram_mirror_vin[17];

// Block Configuration Table
const dev_nvm_block_config_t dev_nvm_block_config_table[DEV_NVM_MAX_BLOCKS] = {
    // Vehicle Identification Number
    {
        .block_id = NVM_BLOCK_VIN,
        .block_size = 17,
        .rom_address = rom_default_vin,
        .ram_address = ram_mirror_vin,
        .block_type = DEV_NVM_BLOCK_NATIVE,
        .write_protection = false,
        .use_crc = true
    }
};

const uint16_t dev_nvm_block_config_count = DEV_NVM_MAX_BLOCKS;
