/**
 * @file DID_PBCfg.h
 * @brief DID Registry Declarations
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 * Generated by: GachBoot ConfigTool (DID Module)
 * Project: GachBoot v1.0.0
 * Generated: 2025-12-06 14:05:23
 */

#ifndef DID_PBCFG_H
#define DID_PBCFG_H

#include <stdint.h>
#include "dev_common.h"
#include "svc_dcm.h"
#include <string.h>
#include "uds_did_registry.h"
// DID Identifiers
#define DID_VIN  0xF190

// Total DID count
#define UDS_DID_COUNT_GENERATED 1

// Generated DID Registry
extern const uds_did_entry_t uds_did_registry_generated[UDS_DID_COUNT_GENERATED];

#endif // DID_PBCFG_H
