/**
 * @file Os_PBCfg.h
 * @brief OS Task Configuration - Auto-generated
 * 
 * This file is auto-generated by GachBoot ConfigTool.
 * DO NOT EDIT MANUALLY!
 * 
 * NOTE: This file uses only standard libraries.
 *       Static library (dev_os.c) will include this file.
 * 
 * Project: GachBoot
 * Generated: [timestamp]
 */

#ifndef OS_PBCFG_H
#define OS_PBCFG_H

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

/* ===== Configuration Metadata ===== */

#define OS_CFG_INIT_TASK_COUNT      1u
#define OS_CFG_CYCLIC_TASK_COUNT    2u
#define OS_CFG_BG_TASK_COUNT        2u

/* ===== Type Definitions (local, must match dev_os.h) ===== */

/** Task function pointer type */
typedef void (*os_cfg_task_func_t)(void);

/** Cycle time enumeration (values must match dev_os_cycle_t) */
typedef enum {
    OS_CFG_CYCLE_1MS    = 0u,
    OS_CFG_CYCLE_10MS   = 1u,
    OS_CFG_CYCLE_20MS   = 2u,
    OS_CFG_CYCLE_100MS  = 3u,
    OS_CFG_CYCLE_1000MS = 4u
} os_cfg_cycle_t;

/* ===== Task Configuration Structures ===== */

typedef struct {
    os_cfg_task_func_t func;
    const char *name;
} os_cfg_task_t;

typedef struct {
    os_cfg_task_func_t func;
    os_cfg_cycle_t cycle;
    const char *name;
} os_cfg_cyclic_task_t;

/* ===== Task Function Declarations ===== */

// Initialization tasks
extern void svc_app_init(void);

// Cyclic tasks
extern void svc_dcm_main_function(void);  // 10ms
extern void svc_app_1000ms_task(void);  // 1000ms

// Background tasks
extern void dev_com_main_function(void);
extern void dev_com_tp_main_function(void);

/* ===== Task Configuration Tables ===== */

/**
 * @brief Initialization task configuration table
 * Tasks are executed in the order defined below
 */
#define OS_INIT_TASKS_CONFIG \
    { \
        {svc_app_init, "svc_app_init"} \
    }

/**
 * @brief Cyclic task configuration table
 * Format: {function, cycle, name}
 */
#define OS_CYCLIC_TASKS_CONFIG \
    { \
        {svc_dcm_main_function, OS_CFG_CYCLE_10MS, "svc_dcm_main_function"}, \
        {svc_app_1000ms_task, OS_CFG_CYCLE_1000MS, "svc_app_1000ms_task"} \
    }

/**
 * @brief Background task configuration table
 * Format: {function, name}
 */
#define OS_BG_TASKS_CONFIG \
    { \
        {dev_com_main_function, "dev_com_main_function"}, \
        {dev_com_tp_main_function, "dev_com_tp_main_function"} \
    }

/*============================================================================*/
/* EXTERN DECLARATIONS                                                       */
/*============================================================================*/

extern const os_cfg_task_t g_os_init_tasks[];
extern const os_cfg_cyclic_task_t g_os_cyclic_tasks[];
extern const os_cfg_task_t g_os_bg_tasks[];
extern const size_t g_os_init_tasks_count;
extern const size_t g_os_cyclic_tasks_count;
extern const size_t g_os_bg_tasks_count;

/*============================================================================*/
/* PUBLIC API DECLARATIONS                                                   */
/*============================================================================*/

/**
 * @brief Execute all initialization tasks
 * @note Called by dev_os during initialization
 */
void os_config_run_init_tasks(void);

/**
 * @brief Execute cyclic tasks for specified cycle
 * @param cycle Cycle time (1ms, 10ms, etc.)
 * @note Called by dev_os from timer ISR
 */
void os_config_run_cyclic_tasks(os_cfg_cycle_t cycle);

/**
 * @brief Execute all background tasks
 * @note Called by dev_os in main loop
 */
void os_config_run_bg_tasks(void);

#endif // OS_PBCFG_H
