/**
 * @file Os_PBCfg.c
 * @brief OS Task Configuration Data - Auto-generated
 * 
 * This file is auto-generated by GachBoot ConfigTool.
 * DO NOT EDIT MANUALLY!
 * 
 * This file contains ONLY configuration data.
 * The static library (dev_os.c) will include Os_PBCfg.h to use this data.
 * 
 * Project: GachBoot
 * Generated: [timestamp]
 */

#include "Os_PBCfg.h"

/* ===== Task Configuration Tables ===== */

const os_cfg_task_t g_os_init_tasks[] = OS_INIT_TASKS_CONFIG;
const os_cfg_cyclic_task_t g_os_cyclic_tasks[] = OS_CYCLIC_TASKS_CONFIG;
const os_cfg_task_t g_os_bg_tasks[] = OS_BG_TASKS_CONFIG;

/* ===== Array Size Constants ===== */
const size_t g_os_init_tasks_count = OS_CFG_INIT_TASK_COUNT;
const size_t g_os_cyclic_tasks_count = OS_CFG_CYCLIC_TASK_COUNT;
const size_t g_os_bg_tasks_count = OS_CFG_BG_TASK_COUNT;

/* ===== Task Execution APIs ===== */

void os_config_run_init_tasks(void)
{
    for (size_t i = 0; i < g_os_init_tasks_count; i++) {
        if (g_os_init_tasks[i].func != 0) {
            g_os_init_tasks[i].func();
        }
    }
}

void os_config_run_cyclic_tasks(os_cfg_cycle_t cycle)
{
    for (size_t i = 0; i < g_os_cyclic_tasks_count; i++) {
        if (g_os_cyclic_tasks[i].func != 0 && g_os_cyclic_tasks[i].cycle == cycle) {
            g_os_cyclic_tasks[i].func();
        }
    }
}

void os_config_run_bg_tasks(void)
{
    for (size_t i = 0; i < g_os_bg_tasks_count; i++) {
        if (g_os_bg_tasks[i].func != 0) {
            g_os_bg_tasks[i].func();
        }
    }
}

