#ifndef BL_HW_CONFIG_H
#define BL_HW_CONFIG_H

#define BL_PLATFORM_UART_TIMEOUT_MS      100u
#define BL_PLATFORM_FLASH_WRITE_ALIGN    32u

#define BL_BOOT_MODE_GPIO_PORT           GPIOC
#define BL_BOOT_MODE_GPIO_PIN            GPIO_PIN_9
#define BL_BOOT_MODE_GPIO_PULL           GPIO_PULLUP
#define BL_BOOT_MODE_ACTIVE_STATE        GPIO_PIN_RESET

#endif /* BL_HW_CONFIG_H */
