#ifndef BL_SECURITY_CONFIG_H
#define BL_SECURITY_CONFIG_H

#define BL_SIGNATURE_ALGORITHM_NONE      0u
#define BL_SIGNATURE_ALGORITHM_ECDSA     1u
#define BL_SELECTED_SIGNATURE_ALGO       BL_SIGNATURE_ALGORITHM_NONE
#define BL_SIGNATURE_MAX_SIZE            96u

#endif /* BL_SECURITY_CONFIG_H */
