#!/usr/bin/env python3
"""
CMake Module - Generate CMakeLists.txt for generated code
"""

from datetime import datetime
import os


def generate_cmake_file(output_path: str, project_name: str, version: str) -> str:
    """Generate CMakeLists.txt for generated code"""
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    content = f"""# Generated Code CMakeLists.txt
# Auto-generated by GachBoot ConfigTool
# Project: {project_name} v{version}
# Generated: {timestamp}

cmake_minimum_required(VERSION 3.22)

# Collect all generated sources
set(GENERATED_SOURCES "")

# Add NvM Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/NvM_Gen)
    file(GLOB NVM_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/NvM_Gen/*.c"
    )
    list(APPEND GENERATED_SOURCES ${{NVM_GEN_SOURCES}})
    message(STATUS "Added NvM_Gen sources: ${{NVM_GEN_SOURCES}}")
endif()

# Add DID Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/DID_Gen)
    file(GLOB DID_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/DID_Gen/*.c"
    )
    list(APPEND GENERATED_SOURCES ${{DID_GEN_SOURCES}})
    message(STATUS "Added DID_Gen sources: ${{DID_GEN_SOURCES}}")
endif()

# Add DCM Session Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/DCM_Session_Gen)
    file(GLOB DCM_SESSION_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/DCM_Session_Gen/*.c"
    )
    list(APPEND GENERATED_SOURCES ${{DCM_SESSION_GEN_SOURCES}})
    message(STATUS "Added DCM_Session_Gen sources: ${{DCM_SESSION_GEN_SOURCES}}")
endif()

# Add Security Access Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Security_Gen)
    file(GLOB SECURITY_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/Security_Gen/*.c"
    )
    list(APPEND GENERATED_SOURCES ${{SECURITY_GEN_SOURCES}})
    message(STATUS "Added Security_Gen sources: ${{SECURITY_GEN_SOURCES}}")
endif()

# Add DCM Service Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Service_Gen)
    file(GLOB SERVICE_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/Service_Gen/*.c"
    )
    # Exclude Service_PBCfg.c (compiled with svc_dcm to resolve circular dependency)
    list(FILTER SERVICE_GEN_SOURCES EXCLUDE REGEX "Service_PBCfg\\.c$")
    list(APPEND GENERATED_SOURCES ${{SERVICE_GEN_SOURCES}})
    message(STATUS "Added Service_Gen sources: ${{SERVICE_GEN_SOURCES}}")
endif()

# Add Routine Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Routine_Gen)
    file(GLOB ROUTINE_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/Routine_Gen/*.c"
    )
    # Exclude Routine_PBCfg.c (compiled with svc_dcm to resolve circular dependency)
    list(FILTER ROUTINE_GEN_SOURCES EXCLUDE REGEX "Routine_PBCfg\\.c$")
    list(APPEND GENERATED_SOURCES ${{ROUTINE_GEN_SOURCES}})
    message(STATUS "Added Routine_Gen sources: ${{ROUTINE_GEN_SOURCES}}")
endif()

# Add Flash Driver Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Fls_Gen)
    file(GLOB FLS_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/Fls_Gen/*.c"
    )
    list(APPEND GENERATED_SOURCES ${{FLS_GEN_SOURCES}})
    message(STATUS "Added Fls_Gen sources: ${{FLS_GEN_SOURCES}}")
endif()

# Add Fee Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Fee_Gen)
    file(GLOB FEE_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/Fee_Gen/*.c"
    )
    list(APPEND GENERATED_SOURCES ${{FEE_GEN_SOURCES}})
    message(STATUS "Added Fee_Gen sources: ${{FEE_GEN_SOURCES}}")
endif()

# Add Memory Layout Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Memory_Layout_Gen)
    # Memory_Layout_Config.h is header-only, no .c files to compile
    message(STATUS "Added Memory_Layout_Gen include directory")
endif()

# Add Memory Layout Generated Code (header-only)
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Memory_Layout_Gen)
    message(STATUS "Added Memory_Layout_Gen include directory")
endif()

# Add OS Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Os_Gen)
    file(GLOB OS_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/Os_Gen/*.c"
    )
    list(APPEND GENERATED_SOURCES ${{OS_GEN_SOURCES}})
    message(STATUS "Added Os_Gen sources: ${{OS_GEN_SOURCES}}")
endif()

# Create library from generated code
add_library(GenerateCode STATIC ${{GENERATED_SOURCES}})

# Add include directories (only if folders exist)
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/NvM_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/NvM_Gen
    )
endif()

if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/DID_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/DID_Gen
    )
endif()

if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Routine_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/Routine_Gen
    )
endif()

if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/DCM_Session_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/DCM_Session_Gen
    )
endif()

if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Security_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/Security_Gen
    )
endif()

if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Service_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/Service_Gen
    )
endif()

if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Fls_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/Fls_Gen
    )
endif()

if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Fee_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/Fee_Gen
    )
endif()

if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Memory_Layout_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/Memory_Layout_Gen
    )
endif()

if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Os_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/Os_Gen
    )
endif()

# Link dependencies
target_link_libraries(GenerateCode PUBLIC stm32cubemx)
"""
    
    cmake_file = os.path.join(output_path, "CMakeLists.txt")
    with open(cmake_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return cmake_file


def generate_cmake_code(config_data: dict, output_dir: str) -> tuple:
    """
    Generate CMakeLists.txt for GenerateCode directory.
    
    Args:
        config_data: Full configuration dictionary
        output_dir: Base output directory (usually "GenerateCode/")
    
    Returns:
        (success: bool, messages: List[str])
    """
    try:
        project = config_data.get('project', {})
        project_name = project.get('name', 'GachBoot')
        version = project.get('version', '1.0.0')
        
        cmake_file = generate_cmake_file(output_dir, project_name, version)
        
        return True, [
            f"Generated: {cmake_file}",
            "CMakeLists.txt will auto-detect all *_Gen folders"
        ]
    except Exception as e:
        return False, [f"CMake generation failed: {str(e)}"]
