#!/usr/bin/env python3
"""
CMake Module - Generate CMakeLists.txt for generated code
"""

from datetime import datetime
import os


def generate_cmake_file(output_path: str, project_name: str, version: str) -> str:
    """Generate CMakeLists.txt for generated code"""
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    content = f"""# Generated Code CMakeLists.txt
# Auto-generated by GachBoot ConfigTool
# Project: {project_name} v{version}
# Generated: {timestamp}

cmake_minimum_required(VERSION 3.22)

# Collect all generated sources
set(GENERATED_SOURCES "")

# Add NvM Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/NvM_Gen)
    file(GLOB NVM_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/NvM_Gen/*.c"
    )
    list(APPEND GENERATED_SOURCES ${{NVM_GEN_SOURCES}})
    message(STATUS "Added NvM_Gen sources: ${{NVM_GEN_SOURCES}}")
endif()

# Add DID Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/DID_Gen)
    file(GLOB DID_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/DID_Gen/*.c"
    )
    list(APPEND GENERATED_SOURCES ${{DID_GEN_SOURCES}})
    message(STATUS "Added DID_Gen sources: ${{DID_GEN_SOURCES}}")
endif()

# Add DCM Session Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/DCM_Session_Gen)
    file(GLOB DCM_SESSION_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/DCM_Session_Gen/*.c"
    )
    list(APPEND GENERATED_SOURCES ${{DCM_SESSION_GEN_SOURCES}})
    message(STATUS "Added DCM_Session_Gen sources: ${{DCM_SESSION_GEN_SOURCES}}")
endif()

# Add Security Access Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Security_Gen)
    file(GLOB SECURITY_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/Security_Gen/*.c"
    )
    list(APPEND GENERATED_SOURCES ${{SECURITY_GEN_SOURCES}})
    message(STATUS "Added Security_Gen sources: ${{SECURITY_GEN_SOURCES}}")
endif()

# Add DCM Service Generated Code
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Service_Gen)
    file(GLOB SERVICE_GEN_SOURCES 
        "${{CMAKE_CURRENT_SOURCE_DIR}}/Service_Gen/*.c"
    )
    list(APPEND GENERATED_SOURCES ${{SERVICE_GEN_SOURCES}})
    message(STATUS "Added Service_Gen sources: ${{SERVICE_GEN_SOURCES}}")
endif()

# Create library from generated code
add_library(GenerateCode STATIC ${{GENERATED_SOURCES}})

# Add include directories (only if folders exist)
if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/NvM_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/NvM_Gen
    )
endif()

if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/DID_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/DID_Gen
    )
endif()

if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/DCM_Session_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/DCM_Session_Gen
    )
endif()

if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Security_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/Security_Gen
    )
endif()

if(EXISTS ${{CMAKE_CURRENT_SOURCE_DIR}}/Service_Gen)
    target_include_directories(GenerateCode PUBLIC
        ${{CMAKE_CURRENT_SOURCE_DIR}}/Service_Gen
    )
endif()

# Link dependencies
target_link_libraries(GenerateCode PUBLIC stm32cubemx)
"""
    
    cmake_file = os.path.join(output_path, "CMakeLists.txt")
    with open(cmake_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return cmake_file
