"""
OS Module - Task Scheduler Configuration
Generates dev_os_config.h with task definitions
"""

def validate_os_config(config):
    """Validate OS configuration
    
    Args:
        config: Dictionary containing os_tasks list
        
    Returns:
        Tuple of (is_valid, errors_list)
    """
    errors = []
    
    # Validate tasks
    tasks = config.get('os_tasks', [])
    
    # Track duplicate function names
    func_names = set()
    
    for i, task in enumerate(tasks):
        task_type = task.get('task_type', '')
        func_name = task.get('function_name', '')
        task_name = task.get('task_name', '')
        
        # Required fields
        if not task_type:
            errors.append(f"Task {i}: Missing task_type")
        elif task_type not in ['init', 'cyclic', 'background']:
            errors.append(f"Task {i}: Invalid task_type '{task_type}'. Must be 'init', 'cyclic', or 'background'")
        
        if not func_name:
            errors.append(f"Task {i}: Missing function_name")
        elif func_name in func_names:
            errors.append(f"Task {i}: Duplicate function_name '{func_name}'")
        else:
            func_names.add(func_name)
        
        if not task_name:
            errors.append(f"Task {i}: Missing task_name")
        
        # Cyclic tasks must have cycle_time
        if task_type == 'cyclic':
            cycle_time = task.get('cycle_time')
            if not cycle_time:
                errors.append(f"Task {i} ({task_name}): Cyclic task must have cycle_time")
            elif cycle_time not in [1, 10, 20, 100, 1000]:
                errors.append(f"Task {i} ({task_name}): Invalid cycle_time '{cycle_time}'. Must be 1, 10, 20, 100, or 1000 (ms)")
    
    return (len(errors) == 0, errors)


def generate_os_config(config, output_dir):
    """Generate OS configuration header file
    
    Args:
        config: Full configuration dictionary
        output_dir: Output directory path
        
    Returns:
        List of generated file paths
    """
    import os
    
    tasks = config.get('os_tasks', [])
    
    # Group tasks by type
    init_tasks = [t for t in tasks if t.get('task_type') == 'init']
    cyclic_tasks = [t for t in tasks if t.get('task_type') == 'cyclic']
    bg_tasks = [t for t in tasks if t.get('task_type') == 'background']
    
    # Group cyclic tasks by cycle time
    cyclic_by_cycle = {
        1: [],
        10: [],
        20: [],
        100: [],
        1000: []
    }
    
    for task in cyclic_tasks:
        cycle = task.get('cycle_time', 10)
        if cycle in cyclic_by_cycle:
            cyclic_by_cycle[cycle].append(task)
    
    generated_files = []
    
    # Create Os_Gen subfolder (follows naming convention like NvM_Gen, DID_Gen, etc.)
    os_gen_dir = os.path.join(output_dir, 'Os_Gen')
    os.makedirs(os_gen_dir, exist_ok=True)
    
    # Generate header file ONLY (no .c file - static lib will include this)
    header_file = os.path.join(os_gen_dir, 'Os_PBCfg.h')
    with open(header_file, 'w') as f:
        f.write(generate_os_header(config, init_tasks, cyclic_tasks, bg_tasks, cyclic_by_cycle))
    generated_files.append(header_file)
    
    return generated_files


def generate_os_header(config, init_tasks, cyclic_tasks, bg_tasks, cyclic_by_cycle):
    """Generate OS configuration header content - NO static lib dependencies"""
    
    project_name = config.get('project', {}).get('name', 'GachBoot')
    
    # Cycle time enum values (local definition, must match dev_os.h)
    cycle_enum_map = {
        1: 'OS_CFG_CYCLE_1MS',
        10: 'OS_CFG_CYCLE_10MS',
        20: 'OS_CFG_CYCLE_20MS',
        100: 'OS_CFG_CYCLE_100MS',
        1000: 'OS_CFG_CYCLE_1000MS'
    }
    
    content = f'''/**
 * @file Os_PBCfg.h
 * @brief OS Task Configuration - Auto-generated
 * 
 * This file is auto-generated by GachBoot ConfigTool.
 * DO NOT EDIT MANUALLY!
 * 
 * NOTE: This file uses only standard libraries.
 *       Static library (dev_os.c) will include this file.
 * 
 * Project: {project_name}
 * Generated: [timestamp]
 */

#ifndef OS_PBCFG_H
#define OS_PBCFG_H

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

/* ===== Configuration Metadata ===== */

#define OS_CFG_INIT_TASK_COUNT      {len(init_tasks)}u
#define OS_CFG_CYCLIC_TASK_COUNT    {len(cyclic_tasks)}u
#define OS_CFG_BG_TASK_COUNT        {len(bg_tasks)}u

/* ===== Type Definitions (local, must match dev_os.h) ===== */

/** Task function pointer type */
typedef void (*os_cfg_task_func_t)(void);

/** Cycle time enumeration (values must match dev_os_cycle_t) */
typedef enum {{
    OS_CFG_CYCLE_1MS    = 0u,
    OS_CFG_CYCLE_10MS   = 1u,
    OS_CFG_CYCLE_20MS   = 2u,
    OS_CFG_CYCLE_100MS  = 3u,
    OS_CFG_CYCLE_1000MS = 4u
}} os_cfg_cycle_t;

/* ===== Task Configuration Structures ===== */

typedef struct {{
    os_cfg_task_func_t func;
    const char *name;
}} os_cfg_task_t;

typedef struct {{
    os_cfg_task_func_t func;
    os_cfg_cycle_t cycle;
    const char *name;
}} os_cfg_cyclic_task_t;

/* ===== Task Function Declarations ===== */

'''
    
    # Declare all task functions
    if init_tasks:
        content += "// Initialization tasks\n"
        for task in init_tasks:
            content += f"extern void {task['function_name']}(void);\n"
        content += "\n"
    
    if cyclic_tasks:
        content += "// Cyclic tasks\n"
        for task in cyclic_tasks:
            content += f"extern void {task['function_name']}(void);  // {task['cycle_time']}ms\n"
        content += "\n"
    
    if bg_tasks:
        content += "// Background tasks\n"
        for task in bg_tasks:
            content += f"extern void {task['function_name']}(void);\n"
        content += "\n"
    
    # Generate configuration tables as macros
    content += "/* ===== Task Configuration Tables ===== */\n\n"
    
    # Init tasks config
    if init_tasks:
        content += "/**\n"
        content += " * @brief Initialization task configuration table\n"
        content += " * Tasks are executed in the order defined below\n"
        content += " */\n"
        content += "#define OS_INIT_TASKS_CONFIG \\\n    { \\\n"
        for i, task in enumerate(init_tasks):
            is_last = (i == len(init_tasks) - 1)
            if is_last:
                content += f"        {{{task['function_name']}, \"{task['task_name']}\"}} \\\n"
            else:
                content += f"        {{{task['function_name']}, \"{task['task_name']}\"}}, \\\n"
        content += "    }\n\n"
    else:
        content += "#define OS_INIT_TASKS_CONFIG    { {0, 0} }\n\n"
    
    # Cyclic tasks config
    if cyclic_tasks:
        content += "/**\n"
        content += " * @brief Cyclic task configuration table\n"
        content += " * Format: {function, cycle, name}\n"
        content += " */\n"
        content += "#define OS_CYCLIC_TASKS_CONFIG \\\n    { \\\n"
        
        # Collect all cyclic tasks
        task_lines = []
        for cycle_ms in [1, 10, 20, 100, 1000]:
            cycle_tasks = cyclic_by_cycle.get(cycle_ms, [])
            for task in cycle_tasks:
                task_lines.append((task['function_name'], cycle_enum_map[cycle_ms], task['task_name']))
        
        for i, (func, cycle, name) in enumerate(task_lines):
            is_last = (i == len(task_lines) - 1)
            if is_last:
                content += f"        {{{func}, {cycle}, \"{name}\"}} \\\n"
            else:
                content += f"        {{{func}, {cycle}, \"{name}\"}}, \\\n"
        
        content += "    }\n\n"
    else:
        content += "#define OS_CYCLIC_TASKS_CONFIG    { {0, 0, 0} }\n\n"
    
    # Background tasks config
    if bg_tasks:
        content += "/**\n"
        content += " * @brief Background task configuration table\n"
        content += " * Format: {function, name}\n"
        content += " */\n"
        content += "#define OS_BG_TASKS_CONFIG \\\n    { \\\n"
        for i, task in enumerate(bg_tasks):
            is_last = (i == len(bg_tasks) - 1)
            if is_last:
                content += f"        {{{task['function_name']}, \"{task['task_name']}\"}} \\\n"
            else:
                content += f"        {{{task['function_name']}, \"{task['task_name']}\"}}, \\\n"
        content += "    }\n\n"
    else:
        content += "#define OS_BG_TASKS_CONFIG    { {0, 0} }\n\n"
    
    # Extern declarations for data arrays (defined in Os_PBCfg.c)
    content += "/*============================================================================*/\n"
    content += "/* EXTERN DECLARATIONS                                                       */\n"
    content += "/*============================================================================*/\n\n"
    content += "extern const os_cfg_task_t g_os_init_tasks[];\n"
    content += "extern const os_cfg_cyclic_task_t g_os_cyclic_tasks[];\n"
    content += "extern const os_cfg_task_t g_os_bg_tasks[];\n"
    content += f"extern const size_t g_os_init_tasks_count;\n"
    content += f"extern const size_t g_os_cyclic_tasks_count;\n"
    content += f"extern const size_t g_os_bg_tasks_count;\n\n"
    
    # Task execution API declarations
    content += "/*============================================================================*/\n"
    content += "/* PUBLIC API DECLARATIONS                                                   */\n"
    content += "/*============================================================================*/\n\n"
    content += "/**\n"
    content += " * @brief Execute all initialization tasks\n"
    content += " * @note Called by dev_os during initialization\n"
    content += " */\n"
    content += "void os_config_run_init_tasks(void);\n\n"
    
    content += "/**\n"
    content += " * @brief Execute cyclic tasks for specified cycle\n"
    content += " * @param cycle Cycle time (1ms, 10ms, etc.)\n"
    content += " * @note Called by dev_os from timer ISR\n"
    content += " */\n"
    content += "void os_config_run_cyclic_tasks(os_cfg_cycle_t cycle);\n\n"
    
    content += "/**\n"
    content += " * @brief Execute all background tasks\n"
    content += " * @note Called by dev_os in main loop\n"
    content += " */\n"
    content += "void os_config_run_bg_tasks(void);\n\n"
    
    # Close header guard
    content += '''#endif // OS_PBCFG_H
'''
    
    return content


def generate_os_source(config, init_tasks, cyclic_tasks, bg_tasks):
    """Generate OS configuration source file - DATA ONLY, no API calls"""
    
    project_name = config.get('project', {}).get('name', 'GachBoot')
    
    content = f'''/**
 * @file Os_PBCfg.c
 * @brief OS Task Configuration Data - Auto-generated
 * 
 * This file is auto-generated by GachBoot ConfigTool.
 * DO NOT EDIT MANUALLY!
 * 
 * This file contains ONLY configuration data.
 * The static library (dev_os.c) will include Os_PBCfg.h to use this data.
 * 
 * Project: {project_name}
 * Generated: [timestamp]
 */

#include "Os_PBCfg.h"

/* ===== Task Configuration Tables ===== */

'''
    
    # Define task tables as const arrays (not static - need to be accessible)
    if init_tasks:
        content += "const os_cfg_task_t g_os_init_tasks[] = OS_INIT_TASKS_CONFIG;\n"
    else:
        content += "const os_cfg_task_t g_os_init_tasks[1] = {{0}};\n"
    
    if cyclic_tasks:
        content += "const os_cfg_cyclic_task_t g_os_cyclic_tasks[] = OS_CYCLIC_TASKS_CONFIG;\n"
    else:
        content += "const os_cfg_cyclic_task_t g_os_cyclic_tasks[1] = {{0}};\n"
    
    if bg_tasks:
        content += "const os_cfg_task_t g_os_bg_tasks[] = OS_BG_TASKS_CONFIG;\n"
    else:
        content += "const os_cfg_task_t g_os_bg_tasks[1] = {{0}};\n"
    
    content += "\n"
    
    # Count variables
    content += "/* ===== Array Size Constants ===== */\n"
    content += f"const size_t g_os_init_tasks_count = {len(init_tasks) if init_tasks else 0};\n"
    content += f"const size_t g_os_cyclic_tasks_count = {len(cyclic_tasks) if cyclic_tasks else 0};\n"
    content += f"const size_t g_os_bg_tasks_count = {len(bg_tasks) if bg_tasks else 0};\n"
    content += "\n"
    
    # Task execution APIs (static lib will call these)
    content += "/* ===== Task Execution APIs ===== */\n\n"
    
    # Init tasks execution
    content += "void os_config_run_init_tasks(void)\n"
    content += "{\n"
    content += "    for (size_t i = 0; i < g_os_init_tasks_count; i++) {\n"
    content += "        if (g_os_init_tasks[i].func != 0) {\n"
    content += "            g_os_init_tasks[i].func();\n"
    content += "        }\n"
    content += "    }\n"
    content += "}\n\n"
    
    # Cyclic tasks execution
    content += "void os_config_run_cyclic_tasks(os_cfg_cycle_t cycle)\n"
    content += "{\n"
    content += "    for (size_t i = 0; i < g_os_cyclic_tasks_count; i++) {\n"
    content += "        if (g_os_cyclic_tasks[i].func != 0 && g_os_cyclic_tasks[i].cycle == cycle) {\n"
    content += "            g_os_cyclic_tasks[i].func();\n"
    content += "        }\n"
    content += "    }\n"
    content += "}\n\n"
    
    # Background tasks execution
    content += "void os_config_run_bg_tasks(void)\n"
    content += "{\n"
    content += "    for (size_t i = 0; i < g_os_bg_tasks_count; i++) {\n"
    content += "        if (g_os_bg_tasks[i].func != 0) {\n"
    content += "            g_os_bg_tasks[i].func();\n"
    content += "        }\n"
    content += "    }\n"
    content += "}\n"
    
    return content
