#!/usr/bin/env python3
"""
Session Module - Validation and Code Generation for Diagnostic Sessions
"""

from typing import Dict, List, Tuple
from datetime import datetime

sessionTypedefs = """

/**
 * @brief Diagnostic Session Configuration Types
 */

typedef struct {
    const char *session_name;           // Session name (for debugging)
    uint8_t session_value;              // Session value (hex)
    uint32_t session_mask;              // Session mask (1 << session_value)
} svc_dcm_session_config_t;
"""

class SessionValidator:
    """Validator for diagnostic sessions configuration"""
    
    def __init__(self):
        self.errors = []
        self.warnings = []
    
    def validate(self, sessions: List[Dict]) -> Tuple[bool, List[str], List[str]]:
        """Validate diagnostic sessions"""
        self.errors = []
        self.warnings = []
        
        if not sessions:
            self.warnings.append("No diagnostic sessions defined")
            return (True, self.errors, self.warnings)
        
        session_ids = set()
        session_names = set()
        session_values = set()
        
        for i, session in enumerate(sessions):
            self._validate_session(i, session, session_ids, session_names, session_values)
        
        return (len(self.errors) == 0, self.errors, self.warnings)
    
    def _validate_session(self, index: int, session: Dict, session_ids: set, session_names: set, session_values: set):
        """Validate single diagnostic session"""
        # Session Name
        if 'session_name' not in session:
            self.errors.append(f"Session {index}: missing session_name")
        elif not session['session_name'] or not session['session_name'].isupper():
            self.errors.append(f"Session {index}: session_name must be uppercase")
        elif session['session_name'] in session_names:
            self.errors.append(f"Duplicate session_name: {session['session_name']}")
        else:
            session_names.add(session['session_name'])
        
        # Session Value
        if 'session_value' not in session:
            self.errors.append(f"Session {index}: missing session_value")
        elif not isinstance(session['session_value'], str):
            self.errors.append(f"Session {index}: session_value must be a hex string (e.g., '0x01')")
        else:
            # Parse hex value
            try:
                value_str = session['session_value']
                if value_str.startswith('0x') or value_str.startswith('0X'):
                    value = int(value_str, 16)
                else:
                    value = int(value_str)
                
                if value < 0 or value > 255:
                    self.errors.append(f"Session {index}: session_value must be 0x00-0xFF")
                elif value in session_values:
                    self.errors.append(f"Duplicate session_value: {session['session_value']}")
                else:
                    session_values.add(value)
            except ValueError:
                self.errors.append(f"Session {index}: invalid session_value format: {session['session_value']}")


class SessionGenerator:
    """Code generator for diagnostic sessions"""
    
    def __init__(self, sessions: List[Dict]):
        self.sessions = sessions
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    def generate_header(self) -> str:
        """Generate session configuration header file"""
        header = f"""/**
 * @file DCM_Session_PBCfg.h
 * @brief Diagnostic Session Configuration (Auto-generated)
 * @date {self.timestamp}
 * 
 * DO NOT MODIFY - Generated by ConfigTool
 */

#ifndef DCM_SESSION_PBCFG_H
#define DCM_SESSION_PBCFG_H

#ifdef __cplusplus
extern "C" {{
#endif

#include <stdint.h>
#include <stdbool.h>
{sessionTypedefs}

/* Session Configuration Count */
#define SVC_DCM_SESSION_COUNT  {len(self.sessions)}U

/* Session Value Definitions */
"""
        
        # Generate session value macros
        for session in self.sessions:
            header += f"#define {session['session_name']}_VALUE  {session['session_value']}\n"
        
        header += "\n/* Session Mask Definitions */\n"
        for session in self.sessions:
            # Parse session value to get numeric value for shift
            value_str = session['session_value']
            if value_str.startswith('0x') or value_str.startswith('0X'):
                value = int(value_str, 16)
            else:
                value = int(value_str)
            header += f"#define {session['session_name']}_MASK  (1U << {value}U)\n"
        
        header += """
/* External Configuration Table */
extern const svc_dcm_session_config_t svc_dcm_session_table[SVC_DCM_SESSION_COUNT];

#ifdef __cplusplus
}
#endif

#endif /* DCM_SESSION_PBCFG_H */
"""
        return header
    
    def generate_source(self) -> str:
        """Generate session configuration source file"""
        source = f"""/**
 * @file DCM_Session_PBCfg.c
 * @brief Diagnostic Session Configuration (Auto-generated)
 * @date {self.timestamp}
 * 
 * DO NOT MODIFY - Generated by ConfigTool
 */

#include "DCM_Session_PBCfg.h"

/**
 * @brief Diagnostic Session Configuration Table
 */
const svc_dcm_session_config_t svc_dcm_session_table[SVC_DCM_SESSION_COUNT] = {{
"""
        
        # Generate session configurations
        for i, session in enumerate(self.sessions):
            session_name = session['session_name']
            session_value = session['session_value']
            description = session.get('description', '')
            
            # Parse session value to get numeric value for shift
            value_str = session_value
            if value_str.startswith('0x') or value_str.startswith('0X'):
                value = int(value_str, 16)
            else:
                value = int(value_str)
            
            source += f"""    /* {i}: {session_name} - {description} */
    {{
        .session_name = "{session_name}",
        .session_value = {session_value},
        .session_mask = (1U << {value}U)
    }}"""
            
            if i < len(self.sessions) - 1:
                source += ","
            source += "\n"
        
        source += "};\n"
        return source


def validate_sessions(sessions: List[Dict]) -> Tuple[bool, List[str], List[str]]:
    """Validate diagnostic sessions configuration"""
    validator = SessionValidator()
    return validator.validate(sessions)


def generate_session_code(sessions: List[Dict], output_dir: str) -> bool:
    """Generate session configuration code files"""
    import os
    
    try:
        # Create DCM_Session_Gen subfolder
        session_output_path = os.path.join(output_dir, "DCM_Session_Gen")
        os.makedirs(session_output_path, exist_ok=True)
        
        # Clean old files in DCM_Session_Gen folder
        for old_file in os.listdir(session_output_path):
            old_file_path = os.path.join(session_output_path, old_file)
            if os.path.isfile(old_file_path):
                os.remove(old_file_path)
        
        # Generate files
        generator = SessionGenerator(sessions)
        
        # Write header
        header_path = os.path.join(session_output_path, "DCM_Session_PBCfg.h")
        with open(header_path, 'w', encoding='utf-8') as f:
            f.write(generator.generate_header())
        
        # Write source
        source_path = os.path.join(session_output_path, "DCM_Session_PBCfg.c")
        with open(source_path, 'w', encoding='utf-8') as f:
            f.write(generator.generate_source())
        
        print(f"✓ Generated: {header_path}")
        print(f"✓ Generated: {source_path}")
        return True
        
    except Exception as e:
        print(f"✗ Error generating session code: {e}")
        return False
